sudo: false

language: python

python:
  - 3.4
  - 3.5

install:
  - pip install flake8
  - pip install coveralls

before_script:
  - flake8 --statistics inkpy_jinja

script:
  - coverage run --source=inkpy_jinja setup.py test
  - coverage report

after_success:
  - coverage report --source=inkpy_jinja  --omit="*__init__*" -m inkpy_jinja/*.py -v
