language: python
python:
  - "2.7"
install:
    - pip install flake8 --use-mirrors
    - pip install -e .
    - pip install coveralls
before_script:
    flake8 --statistics src/inkpy
script:
  coverage run src/inkpy/tests/tests.py -v
after_success:
  coveralls
